-- Baseline schema for the Calorie Tracker API.
-- Written in portable SQL so the same migration runs on PostgreSQL (production)
-- and H2 in PostgreSQL-compatibility mode (tests).

CREATE TABLE users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           VARCHAR(255) NOT NULL UNIQUE,
    password_hash   VARCHAR(255) NOT NULL,
    display_name    VARCHAR(255),
    daily_kcal_goal INTEGER,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE foods (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    brand           VARCHAR(255),
    barcode         VARCHAR(64),
    type            VARCHAR(20) NOT NULL,
    source          VARCHAR(20) NOT NULL,
    energy_kcal     DOUBLE PRECISION NOT NULL,
    protein_g       DOUBLE PRECISION,
    carbs_g         DOUBLE PRECISION,
    sugars_g        DOUBLE PRECISION,
    fat_g           DOUBLE PRECISION,
    sat_fat_g       DOUBLE PRECISION,
    fiber_g         DOUBLE PRECISION,
    salt_g          DOUBLE PRECISION,
    serving_size_g  DOUBLE PRECISION,
    owner_user_id   BIGINT REFERENCES users (id),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_foods_type CHECK (type IN ('PACKAGED', 'RAW')),
    CONSTRAINT chk_foods_source CHECK (source IN ('OFF', 'CIQUAL', 'USER'))
);

CREATE INDEX idx_foods_barcode ON foods (barcode);

CREATE TABLE recipes (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               BIGINT NOT NULL REFERENCES users (id),
    name                  VARCHAR(255) NOT NULL,
    number_of_portions    INTEGER NOT NULL,
    total_cooked_weight_g DOUBLE PRECISION,
    updated_at            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted               BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE recipe_ingredients (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id BIGINT NOT NULL REFERENCES recipes (id),
    food_id   BIGINT NOT NULL REFERENCES foods (id),
    grams     DOUBLE PRECISION NOT NULL
);

CREATE TABLE diary_entries (
    id          UUID PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES users (id),
    entry_date  DATE NOT NULL,
    meal_type   VARCHAR(20) NOT NULL,
    source_type VARCHAR(20) NOT NULL,
    food_id     BIGINT REFERENCES foods (id),
    recipe_id   BIGINT REFERENCES recipes (id),
    quantity    DOUBLE PRECISION NOT NULL,
    kcal        DOUBLE PRECISION NOT NULL,
    protein_g   DOUBLE PRECISION,
    carbs_g     DOUBLE PRECISION,
    fat_g       DOUBLE PRECISION,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted     BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT chk_diary_meal CHECK (meal_type IN ('BREAKFAST', 'LUNCH', 'DINNER', 'SNACK')),
    CONSTRAINT chk_diary_source CHECK (source_type IN ('FOOD', 'RECIPE_PORTION'))
);

CREATE INDEX idx_diary_user_date ON diary_entries (user_id, entry_date);
